const UserRecipesTypes = {
  REQUEST_ALL_USER_RECIPES_PENGING: 'REQUEST_ALL_USER_RECIPES_PENGING',
  REQUEST_ALL_USER_RECIPES_SUCCESS: 'REQUEST_ALL_USER_RECIPES_SUCCESS',
  REQUEST_ALL_USER_RECIPES_FAILED: 'REQUEST_ALL_USER_RECIPES_FAILED',
  REQUEST_FILTERED_USER_RECIPES: 'REQUEST_FILTERED_USER_RECIPES'
}

export default UserRecipesTypes;