const UserRecipesTypes = {
  REQUEST_ALL_USER_RECIPES_PENGING: 'REQUEST_ALL_USER_RECIPES_PENGING',
  REQUEST_ALL_USER_RECIPES_SUCCESS: 'REQUEST_ALL_USER_RECIPES_SUCCESS',
  REQUEST_ALL_USER_RECIPES_FAILED: 'REQUEST_ALL_USER_RECIPES_FAILED',
  REQUEST_FILTERED_USER_RECIPES: 'REQUEST_FILTERED_USER_RECIPES',
  SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
  SET_TOTAL_PAGE: 'SET_TOTAL_PAGE',
  CREATE_NEW_RECIPE_FAILED: 'CREATE_NEW_RECIPE_FAILED',
  CREATE_NEW_RECIPE_SUCCESS: 'CREATE_NEW_RECIPE_SUCCESS'
}

export default UserRecipesTypes;