const PublicRecipesTypes = {
  REQUEST_ALL_PUBLIC_RECIPES_PENGING: 'REQUEST_ALL_PUBLIC_RECIPES_PENGING',
  REQUEST_ALL_PUBLIC_RECIPES_SUCCESS: 'REQUEST_ALL_PUBLIC_RECIPES_SUCCESS',
  REQUEST_ALL_PUBLIC_RECIPES_FAILED: 'REQUEST_ALL_PUBLIC_RECIPES_FAILED',
  REQUEST_FILTERED_PUBLIC_RECIPES: 'REQUEST_FILTERED_PUBLIC_RECIPES',
  RESET_PUBLIC_KEYWORD: 'RESET_PUBLIC_KEYWORD',
  SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
  SET_TOTAL_PAGE: 'SET_TOTAL_PAGE'
}

export default PublicRecipesTypes;