const PublicRecipesTypes = {
  REQUEST_ALL_PUBLIC_RECIPES_PENGING: 'REQUEST_ALL_PUBLIC_RECIPES_PENGING',
  REQUEST_ALL_PUBLIC_RECIPES_SUCCESS: 'REQUEST_ALL_PUBLIC_RECIPES_SUCCESS',
  REQUEST_ALL_PUBLIC_RECIPES_FAILED: 'REQUEST_ALL_PUBLIC_RECIPES_FAILED'
}

export default PublicRecipesTypes;