const UpdateRecipeTypes = {
  RECIPE_TO_BE_UPDATE: 'RECIPE_TO_BE_UPDATE',
  RESET_UPDATE_RECIPE: 'RESET_UPDATE_RECIPE',
  UPDATE_RECIPE_PENDING: 'UPDATE_RECIPE_PENDING',
  UPDATE_RECIPE_SUCCESS: 'UPDATE_RECIPE_SUCCESS',
  UPDATE_RECIPE_FAILED: 'UPDATE_RECIPE_FAILED'
}

export default UpdateRecipeTypes;