export const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SIGNUP_NEW_USER_SUCCESS: 'SIGNUP_NEW_USER_SUCCESS',
  SIGNUP_NEW_USER_FAILED: 'SIGNUP_NEW_USER_FAILED',
  UPLOAD_PROFILE_PIC_PENDING: 'UPLOAD_PROFILE_PIC_PENDING',
  UPLOAD_PROFILE_PIC_SUCCESS: 'UPLOAD_PROFILE_PIC_SUCCESS',
  UPLOAD_PROFILE_PIC_FAILED: 'UPLOAD_PROFILE_PIC_FAILED',
  DELETE_PROFILE_PIC_SUCCESS: 'DELETE_PROFILE_PIC_SUCCESS',
  LOGOUT_CURRENT_USER: 'LOGOUT_CURRENT_USER'
};