export const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SIGNUP_NEW_USER_SUCCESS: 'SIGNUP_NEW_USER_SUCCESS',
  SIGNUP_NEW_USER_FAILED: 'SIGNUP_NEW_USER_FAILED',
  LOGOUT_CURRENT_USER: 'LOGOUT_CURRENT_USER'
};