const CreateRecipesTypes = {
  CREATE_NEW_RECIPE_PENDING: 'CREATE_NEW_RECIPE_PENDING',
  CREATE_NEW_RECIPE_SUCCESS: 'CREATE_NEW_RECIPE_SUCCESS',
  CREATE_NEW_RECIPE_FAILED: 'CREATE_NEW_RECIPE_FAILED',
  CREATE_NEW_RECIPE_RESET_STATE: 'CREATE_NEW_RECIPE_RESET_STATE',
  UPLOAD_RECIPE_PIC_PENDING: 'UPLOAD_RECIPE_PIC_PENDING',
  UPLOAD_RECIPE_PIC_SUCCESS: 'UPLOAD_RECIPE_PIC_SUCCESS',
  UPLOAD_RECIPE_PIC_FAILED: 'UPLOAD_RECIPE_PIC_FAILED',
  SET_ON_EDIT_RECIPE_FOR_PHOTO: 'SET_ON_EDIT_RECIPE_FOR_PHOTO'
}

export default CreateRecipesTypes;